### ISSUE TITLE
Decision on project and development management

### ISSUE THREAD

**Issue by uyguronur** [AyranIsTheNewRaki/SWE574#8]
Since we are working as a team we should have some kind of a project and development management that every team member agrees on and every team member should follow. We should create one wiki page about this.

**Comment by uyguronur** [comment]
Hi @cantux @ebolat @erenerdogannn @idilgun @taygungdmr 

I have created one draft document about this. Please review it and write your comments about so that we can come up with a final management decision.

Thanks,
Onur

**Comment by ebolat** [comment]
Great document @uyguronur, I couldn't find any missing points.

**Comment by idilgun** [comment]
Looks very good, thanks @uyguronur

**Comment by erenerdogannn** [comment]
Thank you @uyguronur . Great document.

**Comment by uyguronur** [comment]
Thanks, I am closing this issue then. However we can still discuss this document anytime you want.
